name: Deploy_Test_PROD

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_IP }}
          username: "user"
          key: ${{ secrets.SSH_KEY }}
          port: 22

      - name: Pull latest Docker image
        run: |
          docker pull ${{ vars.DOCKERHUB_USERNAME }}/calculator-app-finished:latest

      - name: Stop running container (if it exists)
        run: |
          if [ "$(docker ps -q -f name=calculator-app-finished)" ]; then
            docker stop calculator-app-finished
          fi
          if [ "$(docker ps -aq -f name=calculator-app-finished)" ]; then
            docker rm calculator-app-finished
          fi

      - name: Run latest container
        run: |
          docker run -d \
            --name calculator-app-finished \
            -p 80:3000 \
            ${{ vars.DOCKERHUB_USERNAME }}/calculator-app-finished:latest
