name: Deploy_Test_PROD

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Production Server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_IP }}
          username: user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/calculator-app-finished:latest

            docker stop calculator-app-finished || true

            docker rm calculator-app-finished || true

            docker run -d --name calculator-app-finished -p 80:3000 ${{ vars.DOCKERHUB_USERNAME }}/calculator-app-finished:latest
