name: Deploy_Test_ENV

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest Docker image
        run: |
          docker pull ${{ vars.DOCKERHUB_USERNAME }}/calculator-app-finished:latest

      - name: Stop running container (if it exists)
        run: |
            sudo docker stop calculator-app-finished || true
            sudo docker rm calculator-app-finished || true

      - name: Run latest container
        run: |
          docker run -d --name calculator-app-finished -p 3000:3000 ${{ vars.DOCKERHUB_USERNAME }}/calculator-app-finished:latest
